<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'id' => '5e2600a0-2851-4536-9167-800a4c2e63e0',
                'name' => 'Opeyemi Temenu',
                'email' => 'opeyemitemenu@gmail.com',
                'password' => null,
                'email_verified_at' => '2024-09-17 19:51:10',
                'email_verification_otp' => 240917,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-09-17 19:36:10',
                'updated_at' => '2024-09-17 19:36:10',
            ],
            [
                'id' => '29cec997-9629-4a1a-b78f-cbf2305cb1c9',
                'name' => 'Opeyemi Temenu',
                'email' => 'temenuo@gmail.com',
                'password' => null,
                'email_verified_at' => '2024-10-15 19:18:36',
                'email_verification_otp' => 909678,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-10-15 19:03:36',
                'updated_at' => '2024-10-15 19:03:36',
            ],
            [
                'id' => '7d0a21ff-b28f-4685-9df3-b83ea846859a',
                'name' => 'Opeyemi Temenu',
                'email' => 'opeyemitem78@gmail.com',
                'password' => '$2a$10$XL0FtOaZiCqubwi1d9N/zumUeJ3XQu1ZfI6KLLCRvwNzuJ2zNC3JC',
                'email_verified_at' => '2024-10-15 19:29:06',
                'email_verification_otp' => 497497,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-10-15 19:14:06',
                'updated_at' => '2024-10-15 19:16:56',
            ],
            [
                'id' => 'bb93d166-8dc9-4e64-8d47-aa936c940731',
                'name' => 'Emma Rios',
                'email' => 'pexynegajo@mailinator.com',
                'password' => null,
                'email_verified_at' => '2024-10-15 19:51:57',
                'email_verification_otp' => 594122,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-10-15 19:36:57',
                'updated_at' => '2024-10-15 19:36:57',
            ],
            [
                'id' => 'ccfb7fc5-c8e0-4b34-af8e-f6ee3fb3929d',
                'name' => 'Jescie Daugherty',
                'email' => 'siwukax@mailinator.com',
                'password' => null,
                'email_verified_at' => '2024-10-15 19:53:06',
                'email_verification_otp' => 761105,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-10-15 19:38:06',
                'updated_at' => '2024-10-15 19:38:06',
            ],
            [
                'id' => '171fda9c-85f1-4756-ba24-5eba5c1356b0',
                'name' => 'Meredith Barr',
                'email' => 'muto@mailinator.com',
                'password' => null,
                'email_verified_at' => '2024-10-15 19:54:13',
                'email_verification_otp' => 412797,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-10-15 19:39:13',
                'updated_at' => '2024-10-15 19:39:13',
            ],
            [
                'id' => 'c3e9dc7c-56b2-4abe-9310-f5fbf4bc77e9',
                'name' => 'Buckminster Nelson',
                'email' => 'mutoooo@mailinator.com',
                'password' => '$2a$10$0IG.LbaZ39eyl.ualp2SZ.P8e735xu4X5Yg4zZfm7fAlHpSRCm1WG',
                'email_verified_at' => '2024-10-15 19:59:23',
                'email_verification_otp' => 398205,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-10-15 19:44:23',
                'updated_at' => '2024-10-15 19:45:03',
            ],
            [
                'id' => '2d7c6175-8764-424c-b818-7b1491e39933',
                'name' => 'John Doe',
                'email' => 'johndoe@example221.com',
                'password' => null,
                'email_verified_at' => '2024-10-16 06:21:16',
                'email_verification_otp' => 468662,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-10-16 06:06:16',
                'updated_at' => '2024-10-16 06:06:16',
            ],
            [
                'id' => '6e7273c3-8d80-40e7-a5b3-99c0238d74c7',
                'name' => 'Louis Hoffman',
                'email' => 'wady@mailinator.com',
                'password' => '$2a$10$z9SzZW762fHH1lPFKE8GKuRUAf/zZRoZW6rykE7zssZO4lT0xX53S',
                'email_verified_at' => '2024-10-19 07:55:43',
                'email_verification_otp' => 878682,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-10-19 07:40:43',
                'updated_at' => '2024-10-19 07:43:37',
            ],
            [
                'id' => '0c4b0e98-4d21-4e05-871f-2e5c2b647424',
                'name' => 'lp 98',
                'email' => 'super@lp98.com',
                'password' => '$2a$10$QDu/TasA1mreGtFiX3vFl.SA/lL3MYBpId5N0JAlIB9XMPksp83QG',
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => true,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-09-11 07:05:33',
                'updated_at' => '2024-10-19 15:04:35',
            ],
            [
                'id' => '9a715ecb-ee3f-4b34-9b9a-6ffcbacdc1c3',
                'name' => 'Tobi Idowu',
                'email' => 'tester@mailinator.com',
                'password' => '$2a$10$fTl8RCO.BXtMmb4AIS2rG.cuY2MZq4GVMuNIifyA5j6aQ5VaQKqlW',
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '09079167476',
                'address' => '18, Adebayo Onile-ere street, Grammar School, ikorodu, lagos',
                'education' => 'Secondary school',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-03-19 07:34:03',
                'updated_at' => '2025-03-19 07:34:03',
            ],
            [
                'id' => 'bd9d338b-60c3-4679-9f6e-3fe52364b89f',
                'name' => 'Michael Stewart',
                'email' => 'veqi@mailinator.com',
                'password' => '$2a$10$QhXpBGL9wbiaHCi6ouc1VONuMsjx6/zURSeNsnfDYwrZcO/5HDYNq',
                'email_verified_at' => '2024-10-24 07:56:09',
                'email_verification_otp' => 687764,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-10-24 07:41:09',
                'updated_at' => '2024-10-24 07:41:43',
            ],
            [
                'id' => 'b6c5d883-6d37-4254-a9c7-2d2a735fe12b',
                'name' => 'Faith Kehinde',
                'email' => 'kehindefaith987@gmail.com',
                'password' => '$2a$10$hamnbqh/A4W9imo64gjh7.sAG44MSyss88yINz4H1LmpgC/vWgpnu',
                'email_verified_at' => '2024-11-10 13:37:59',
                'email_verification_otp' => 528864,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-10 13:22:59',
                'updated_at' => '2024-11-10 13:25:49',
            ],
            [
                'id' => 'ab5f8268-05a8-493e-a72f-2fcf14698205',
                'name' => 'Innocent Oshiole Agekamhe',
                'email' => 'innocentoshiole@gmail.com',
                'password' => '$2a$10$yymCaKUECp34YnuQenRI4OlLRtOCYG499bAs2JjqtB8j8Mn1iobYO',
                'email_verified_at' => '2025-03-21 20:42:32',
                'email_verification_otp' => 202089,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-10 20:21:59',
                'updated_at' => '2025-03-21 20:42:32',
            ],
            [
                'id' => '8dfce97f-d222-411a-805a-f3a0df115537',
                'name' => 'Adelana Adeleye',
                'email' => 'tosdefinft@gmail.com',
                'password' => '$2a$10$HIDbUhX3n9E.WPZ8aPv29OgjEaLfwjveDroYZbf9TE4/9tiH638gO',
                'email_verified_at' => '2025-03-21 18:57:14',
                'email_verification_otp' => 787025,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-10 13:40:09',
                'updated_at' => '2025-03-21 18:57:14',
            ],
            [
                'id' => '0bd11d29-1c9f-4fa7-885e-60d3b2ee60f7',
                'name' => 'Ibukunoluwa Temenu',
                'email' => 'ibk.abbie@gmail.com',
                'password' => '$2a$10$tHsEa7LFm0c5VnZDoWOeUevR0YH5GP1CiJF4VYojqUMoYC6fHMN5i',
                'email_verified_at' => '2025-03-22 08:14:35',
                'email_verification_otp' => 558927,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-10 13:26:37',
                'updated_at' => '2025-03-22 08:14:35',
            ],
            [
                'id' => '9ea5b816-a04e-487a-aae0-ea8a230e54c6',
                'name' => 'Drey Simon',
                'email' => 'drey@mailinator.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => 861047,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '09079162233',
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-18 11:55:25',
                'updated_at' => '2024-11-18 11:55:25',
            ],
            [
                'id' => '3b8f82e9-9ac8-4554-a87e-432280894a78',
                'name' => 'test tete',
                'email' => 'etet@mail.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => 831417,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '08012345566',
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-18 18:59:27',
                'updated_at' => '2024-11-18 18:59:27',
            ],
            [
                'id' => 'a30aed04-1986-4a8b-94f4-093debf8102b',
                'name' => 'John Doe',
                'email' => 'john.doeuu@exampleq.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '1234567890',
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-19 11:11:17',
                'updated_at' => '2024-11-19 11:11:17',
            ],
            [
                'id' => '28038bda-5e40-4990-bcf8-dd30d8ccf1d9',
                'name' => 'Jane Smith',
                'email' => 'jane.smithii@example33.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '1987654321',
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-19 11:11:18',
                'updated_at' => '2024-11-19 11:11:18',
            ],
            [
                'id' => '4ce3aa21-2fb3-4403-9a77-6979282ebe23',
                'name' => 'Test User',
                'email' => 'test@usermail.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '08023185544',
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-19 12:04:27',
                'updated_at' => '2024-11-19 12:04:27',
            ],
            [
                'id' => 'e031cfe3-23f5-469a-908f-0af1b38edfe1',
                'name' => 'Test User',
                'email' => 'test@new.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '8023456678',
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-19 12:05:24',
                'updated_at' => '2024-11-19 12:05:24',
            ],
            [
                'id' => '1b2164d5-7a11-4bec-a81e-bce0f2f00422',
                'name' => 'Tester Users',
                'email' => 'test1@neww.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '8011223345',
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-19 12:05:24',
                'updated_at' => '2024-11-19 12:05:24',
            ],
            [
                'id' => '2b055f17-8af2-4372-9d5d-1ed25f282529',
                'name' => 'Janet Nsogbu',
                'email' => 'janet@nsogbu.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '08022334455',
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-19 12:08:39',
                'updated_at' => '2024-11-19 12:08:39',
            ],
            [
                'id' => '013051fc-550d-4024-a9a8-40190bec5d6b',
                'name' => 'Joel Friday',
                'email' => 'fridayjoel2003@gmail.com',
                'password' => '$2a$10$jwGzr6XwnISpeAXBX0tSsemnvWW30Lh/H89mMher/avwV8IWQhAh6',
                'email_verified_at' => '2024-11-10 20:04:17',
                'email_verification_otp' => 409768,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-10 19:49:17',
                'updated_at' => '2024-11-20 12:56:37',
            ],
            [
                'id' => '1b0d00c7-26bc-4cd2-b629-d781f076f02c',
                'name' => 'Jonathan Michael',
                'email' => 'jonathan@gmail.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '08023334411',
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-26 05:15:34',
                'updated_at' => '2024-11-26 05:15:34',
            ],
            [
                'id' => '30a562e1-afac-469e-b9a5-c3554433cf87',
                'name' => 'Isaac Abraham',
                'email' => 'test@mail101.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '08022334455',
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-29 20:52:58',
                'updated_at' => '2024-11-29 20:52:58',
            ],
            [
                'id' => '908cddc1-23d7-462a-95c8-d9d0d77d49d4',
                'name' => 'James Joe',
                'email' => 'james@joeeeee.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '09079132423',
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-12-06 05:58:36',
                'updated_at' => '2024-12-06 05:58:36',
            ],
            [
                'id' => 'c1a15084-4e9a-484f-9c20-71e6864e3cbe',
                'name' => 'John Doe',
                'email' => 'john.doe@email.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '08023345577',
                'address' => 'Lagos, Nigeria',
                'education' => 'Masters (MSc)',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-01-27 10:10:08',
                'updated_at' => '2025-01-27 10:10:08',
            ],
            [
                'id' => '6489a13c-ca21-4235-bc95-8a61a71ce826',
                'name' => 'Jane Doe',
                'email' => 'jane@tester.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '8022221111',
                'address' => 'Lagos, Nigeria',
                'education' => 'Secondary school',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-01-27 10:17:33',
                'updated_at' => '2025-01-27 10:17:33',
            ],
            [
                'id' => 'd7ef1c46-dc46-4c57-abe5-a91bd37cb2a7',
                'name' => 'Jane Smith',
                'email' => 'smith.jane@mailinator.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '7065542233',
                'address' => 'Lagos, Nigeria',
                'education' => 'Masters',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-01-27 10:22:44',
                'updated_at' => '2025-01-27 10:22:44',
            ],
            [
                'id' => '0b53009e-3c6f-43f0-9704-8a621295bcfe',
                'name' => 'Ope Banke',
                'email' => 'ope.banke@mailinator.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => false,
                'phone_number' => '08075564433',
                'address' => '2, Lowa, Ikorodu',
                'education' => 'Bachelors (BSc)',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-01-27 10:24:09',
                'updated_at' => '2025-01-27 10:24:09',
            ],
            [
                'id' => 'ffdd8209-b94b-4d57-aab7-6bc1223fffd8',
                'name' => 'Pelumi Adeshina',
                'email' => 'pelusco.pa@gmail.com',
                'password' => '$2a$10$5U1k53HmmxfStCbTiLws9eCrGy1Lb9PnELkADtUXZYtotjLATLQPO',
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '07062049358',
                'address' => 'Olayemi estate, Grammer school, Lagos',
                'education' => 'Bachelors (BSc)',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-03-21 19:30:24',
                'updated_at' => '2025-03-21 19:30:24',
            ],
            [
                'id' => '6c2e390f-720f-4889-9731-4d52461fbc25',
                'name' => 'Ryan Collins',
                'email' => 'test@mail.com',
                'password' => '$2a$10$63YicPMbc9JHh3fFRPPzYuHdEq2XxatlhuOa8oEqFIZA3Y4rclrVS',
                'email_verified_at' => '2024-10-26 20:11:04',
                'email_verification_otp' => 808527,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => '2025-03-18 07:33:39',
                'created_at' => '2024-10-26 20:56:04',
                'updated_at' => '2025-03-18 07:33:39',
            ],
            [
                'id' => 'd49826cb-38bf-4236-9886-d292adc66f18',
                'name' => 'Tobi Idowu',
                'email' => 'idtobi8@gmail.com',
                'password' => '$2a$10$nKhJ20Ps4olqBsTUsR2fEuXlaEePxQ9zmUh.G/A40SImzw3fS/1rO',
                'email_verified_at' => '2024-11-06 03:14:00',
                'email_verification_otp' => 764961,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-06 02:59:00',
                'updated_at' => '2025-03-08 09:59:47',
            ],
            [
                'id' => '9ae68535-8330-4eed-bff4-b14cb531668b',
                'name' => 'Phelan Mcdowell',
                'email' => 'diwege@mailinator.com',
                'password' => '$2a$10$.alGBk7aKDZh99WJUuCxMuu6CW./mEzsM8X7ixNXHZakLHlaMZ/bO',
                'email_verified_at' => '2024-10-24 07:09:02',
                'email_verification_otp' => 347111,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => '2025-03-18 16:43:43',
                'created_at' => '2024-10-24 06:54:02',
                'updated_at' => '2025-03-18 16:43:43',
            ],
            [
                'id' => '0eef45ca-861d-49a2-8ec6-4c8d0aee1880',
                'name' => 'Carol Ivory',
                'email' => 'carol-jeantender@indigobook.com',
                'password' => '$2a$10$gX38u.3oOqlsiGTtbpPxSOyC9E.15JYB7P7LYlw5GsA3Z0hv4AXhO',
                'email_verified_at' => '2025-03-19 08:07:47',
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '1234567890',
                'address' => '123 Main St',
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-03-19 07:52:07',
                'updated_at' => '2025-03-19 08:07:47',
            ],
            [
                'id' => '19fd12fb-9674-4836-843a-45d0009d2705',
                'name' => 'Uche Ogbechie',
                'email' => 'uche@example1.com',
                'password' => '$2a$10$r9YxJ/j0T3X.z7NspZ99ReL09/swc/zUidqALFwA8.x373LlsTEfq',
                'email_verified_at' => '2025-03-08 10:37:33',
                'email_verification_otp' => 676214,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '08164529600',
                'address' => '7, Obasanjo road',
                'education' => 'Secondary school',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-03-06 07:18:05',
                'updated_at' => '2025-03-08 10:37:33',
            ],
            [
                'id' => 'c9b240a5-6edb-41f8-8ad4-b6596f486c57',
                'name' => 'New User',
                'email' => 'shariateal@indigobook.com',
                'password' => '$2a$10$rUNznHRYCUmf545RuSFXT..Xs7pK53OGlIP85C2GQmXGGO4CnL9HK',
                'email_verified_at' => '2025-03-08 10:31:53',
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '09079167476',
                'address' => 'Tesre',
                'education' => 'Secondary school',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => '2025-03-08 10:45:17',
                'created_at' => '2025-03-08 10:04:59',
                'updated_at' => '2025-03-08 10:45:17',
            ],
            [
                'id' => '2e5119d6-26d6-470d-9721-9bf7b4740765',
                'name' => 'Tobi Idowu',
                'email' => 'test@mailinator.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '09079167476',
                'address' => '18, Adebayo Onile-ere street, Grammar School, ikorodu, lagos',
                'education' => 'Secondary school',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-03-19 07:10:45',
                'updated_at' => '2025-03-19 07:10:45',
            ],
            [
                'id' => '999a3733-545a-4c26-9009-dea7bee87422',
                'name' => 'Nanny Ivory',
                'email' => 'deliciouschocolate1@indigobook.com',
                'password' => '$2a$10$jAEu9y77Ej5ZuG6nEC4WxeoAbFjzdL6CWzPu/3mqn64Tp/7VmeC/W',
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '1234567890',
                'address' => '123 Main St',
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-03-19 07:21:13',
                'updated_at' => '2025-03-19 07:21:13',
            ],
            [
                'id' => 'd680fbf0-5208-489a-b9c8-064a68d04a87',
                'name' => 'Tobi Idowu',
                'email' => 'tester404444@mailinator.com',
                'password' => null,
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '09079167476',
                'address' => '18, Adebayo Onile-ere street, Grammar School, ikorodu, lagos',
                'education' => 'Secondary school',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-03-19 07:21:14',
                'updated_at' => '2025-03-19 07:21:14',
            ],
            [
                'id' => 'acfdfd1c-c2c4-4000-8ac0-6d0c13da2415',
                'name' => 'Diekoloreoluwa Adekusibe',
                'email' => 'loreolu@gmail.com',
                'password' => '$2a$10$Oqn7zjGIW.Ai1ca9lPE6tO7mwbKgYStN.iFvQJgvJjiva7ovYRzDy',
                'email_verified_at' => '2025-03-21 20:51:45',
                'email_verification_otp' => 949138,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => null,
                'address' => null,
                'education' => null,
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2024-11-10 13:36:41',
                'updated_at' => '2025-03-21 20:51:45',
            ],
            [
                'id' => '9d6c207c-42f2-4d10-8779-f7422324614d',
                'name' => 'test tester',
                'email' => 'tobss101@gmail.com',
                'password' => '$2a$10$Gz7EGuJkiXMhSEu57IBS/O07Mewari7OixsMMZalRnQygNxV9NkkG',
                'email_verified_at' => '2025-03-21 19:54:52',
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '0907 916 7476',
                'address' => 'Aliquip odit do eaqu',
                'education' => 'Bachelors (BSc)',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-03-08 09:32:16',
                'updated_at' => '2025-03-21 19:54:52',
            ],
            [
                'id' => '70263e23-82fe-417e-b206-6bfb051ede82',
                'name' => 'Date Test',
                'email' => 'test@date.com',
                'password' => '$2a$10$2CMM841YWC2/x21Of/6fE.nKJoOpKjN9WgnjD9YA1iCIgJ5peUcmy',
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '09079167476',
                'address' => '18, Adebayo Onile-ere street, Grammar School, ikorodu, lagos',
                'education' => 'Higher National Diploma (HnD)',
                'date_of_birth' => null,
                'gender' => null,
                'occupation' => null,
                'deactivated_at' => null,
                'created_at' => '2025-03-22 10:57:55',
                'updated_at' => '2025-03-22 10:57:55',
            ],
            [
                'id' => '7af88165-3784-4cbf-9fa2-de956738540f',
                'name' => 'Tobi Idowu',
                'email' => 'test500@mailinator.com',
                'password' => '$2a$10$B.VsYPA.8VqISme0urMU5OZPIk/5ep3wm9cQC3R.JqPDJYCwWU/oO',
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '09079167476',
                'address' => '18, Adebayo Onile-ere street, Grammar School, ikorodu, lagos',
                'education' => 'Bachelors (BSc)',
                'date_of_birth' => null,
                'gender' => 'male',
                'occupation' => 'Doctor',
                'deactivated_at' => null,
                'created_at' => '2025-03-28 16:17:40',
                'updated_at' => '2025-03-28 16:17:40',
            ],
            [
                'id' => '43816685-b7da-4b57-a1e4-f90407e6a5d4',
                'name' => 'Tobi Idowu',
                'email' => 'test400@mailinator.com',
                'password' => '$2a$10$nqD1LVYU8VXP8BHalRuSu.VHCUwroI9OVeVpuS9Lbz/jvaAseMkrK',
                'email_verified_at' => null,
                'email_verification_otp' => null,
                'password_reset_otp' => null,
                'password_reset_otp_expire_in' => null,
                'role_id' => null,
                'is_admin' => false,
                'is_super_admin' => true,
                'phone_number' => '09079167476',
                'address' => '18, Adebayo Onile-ere street, Grammar School, ikorodu, lagos',
                'education' => 'Bachelors (BSc)',
                'date_of_birth' => null,
                'gender' => 'male',
                'occupation' => 'Banker',
                'deactivated_at' => null,
                'created_at' => '2025-03-28 16:20:05',
                'updated_at' => '2025-03-28 16:20:05',
            ],
        ];

        // Use upsert to avoid duplicate errors if re-run
        DB::table('users')->upsert($users, ['id'], [
            'name', 'email', 'password', 'email_verified_at', 'email_verification_otp',
            'password_reset_otp', 'password_reset_otp_expire_in', 'role_id',
            'is_admin', 'is_super_admin', 'phone_number', 'address', 'education',
            'date_of_birth', 'gender', 'occupation', 'deactivated_at',
            'created_at', 'updated_at',
        ]);
    }
}
